# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-12-03 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskQueue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasktype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
