# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcontent', '0002_auto_20180124_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer',
        ),
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=200),
        ),
    ]
