# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcontent', '0003_auto_20180124_1452'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
    ]
