# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webcontent', '0007_remove_faq_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faqcategory', to='webcontent.FaqCategory'),
        ),
    ]
