# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcontent', '0012_auto_20180125_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
