# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcontent', '0013_auto_20180125_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='order',
            new_name='flow',
        ),
    ]
