# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-12-06 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0023_auto_20211203_2115'),
        ('webcontent', '0015_auto_20180125_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbackcommunity', to='Community.Community'),
        ),
    ]
