# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcescore',
            name='downvote_value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resourcescore',
            name='publish_value',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='resourcescore',
            name='upvote_value',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
