# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-06 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='author',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='publisher',
            field=models.IntegerField(default=0),
        ),
    ]
