# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityrep',
            name='rep',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systemrep',
            name='sysrep',
            field=models.IntegerField(default=0),
        ),
    ]
