# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 13:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0003_auto_20180607_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defaultvalues',
            old_name='crep_for_art',
            new_name='min_crep_for_art',
        ),
        migrations.RenameField(
            model_name='defaultvalues',
            old_name='srep_for_art',
            new_name='min_srep_for_art',
        ),
        migrations.RenameField(
            model_name='defaultvalues',
            old_name='srep_for_comm',
            new_name='min_srep_for_comm',
        ),
    ]
