# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0004_communityreputaion_published_by_me_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgescore',
            old_name='articles_published_be_me_level_1',
            new_name='articles_published_by_me_level_1',
        ),
        migrations.RenameField(
            model_name='badgescore',
            old_name='articles_published_be_me_level_2',
            new_name='articles_published_by_me_level_2',
        ),
        migrations.RenameField(
            model_name='badgescore',
            old_name='articles_published_be_me_level_3',
            new_name='articles_published_by_me_level_3',
        ),
        migrations.RenameField(
            model_name='badgescore',
            old_name='articles_published_be_me_level_4',
            new_name='articles_published_by_me_level_4',
        ),
        migrations.RenameField(
            model_name='badgescore',
            old_name='articles_published_be_me_level_5',
            new_name='articles_published_by_me_level_5',
        ),
    ]
