# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-11 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0004_auto_20180611_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultvalues',
            name='threshold_cadmin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='defaultvalues',
            name='threshold_publisher',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
