# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-21 11:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BasicArticle', '0020_merge_20180627_1228'),
        ('Reputation', '0004_resourcescore_can_vote_unpublished'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleScoreLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
                ('reported', models.IntegerField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BasicArticle.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleVotedByLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvoted', models.BooleanField(default=False)),
                ('downvoted', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicArticle.Articles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
