# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 05:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0005_auto_20180611_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultvalues',
            name='min_srep_for_art',
        ),
    ]
