# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0005_articlescorelog_articlevotedbylogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcescore',
            name='resource_type',
            field=models.TextField(null=True),
        ),
    ]
