# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0006_resourcescore_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcescore',
            name='resource_type',
            field=models.TextField(default='resource', max_length=20),
        ),
    ]
