# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0007_auto_20180828_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcescore',
            name='resource_type',
            field=models.CharField(default='resource', max_length=20),
        ),
    ]
