# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0007_auto_20180614_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityrep',
            name='rep',
            field=models.IntegerField(default=15),
        ),
    ]
