# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-28 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0010_userscore_role_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscore',
            name='author',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='publisher',
            field=models.IntegerField(null=True),
        ),
    ]
