# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0010_defaultvalues_threshold_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultvalues',
            name='article_report_rejected',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
