# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-30 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0011_auto_20180828_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityreputaion',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
