# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-04 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0012_auto_20180830_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlescorelog',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articlescorelog',
            name='downvote',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articlescorelog',
            name='reported',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='articlescorelog',
            name='upvote',
            field=models.IntegerField(null=True),
        ),
    ]
