# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reputation', '0013_auto_20180626_0846'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultValues',
            new_name='ReputationDashboard',
        ),
    ]
