# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-17 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0014_auto_20180905_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlescorelog',
            old_name='article',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='articlevotedbylogs',
            old_name='article',
            new_name='resource',
        ),
        migrations.AlterField(
            model_name='articlescorelog',
            name='downvote',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='articlescorelog',
            name='reported',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='articlescorelog',
            name='upvote',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
