# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-17 11:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0015_auto_20181017_1109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleVotedByLogs',
            new_name='ArticleUserScoreLogs',
        ),
    ]
