# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-23 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reputation', '0016_auto_20181017_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagReasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MediaScoreLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.IntegerField(default=0, null=True)),
                ('downvote', models.IntegerField(default=0, null=True)),
                ('reported', models.IntegerField(default=0, null=True)),
                ('publish', models.BooleanField(default=False)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Media.Media')),
            ],
        ),
        migrations.CreateModel(
            name='MediaUserScoreLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvoted', models.BooleanField(default=False)),
                ('downvoted', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Media.Media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
