# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-23 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BasicArticle', '0020_merge_20180627_1228'),
        ('Reputation', '0018_auto_20181023_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFlagLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicArticle.Articles')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reputation.FlagReason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFlagLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Media.Media')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reputation.FlagReason')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
