# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-23 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0019_articleflaglogs_mediaflaglogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleflaglogs',
            old_name='article',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='mediaflaglogs',
            old_name='article',
            new_name='resource',
        ),
    ]
