# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-30 18:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0002_auto_20181203_1022'),
        ('Reputation', '0020_auto_20181023_1916'),
    ]

    operations = [
    ]
