# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-30 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0022_auto_20181230_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityreputaion',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
