# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-30 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0023_auto_20181230_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityreputaion',
            name='score',
        ),
        migrations.AddField(
            model_name='communityreputaion',
            name='published_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityreputaion',
            name='vote_log',
            field=models.IntegerField(default=0),
        ),
    ]
