# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-30 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reputation', '0025_auto_20181230_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityreputaion',
            name='vote_log',
        ),
        migrations.AddField(
            model_name='communityreputaion',
            name='downvote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityreputaion',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
