# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_links_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='topics',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_topics', to='Course.Course'),
        ),
    ]
