# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0019_auto_20180227_1138'),
        ('Course', '0003_topics_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_course', to='Community.Community'),
        ),
    ]
