# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_course_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=300)),
                ('desc', models.TextField()),
                ('topics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics_videos', to='Course.Topics')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='community',
        ),
    ]
