# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_auto_20180316_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
