# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-02 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_auto_20180321_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='types',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
