# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-09 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_auto_20180409_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='body',
        ),
    ]
