# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-04 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_topicarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
