# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-16 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20180108_1504'),
        ('Course', '0011_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_workflow', to='workflow.States'),
        ),
    ]
