# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0012_auto_20180530_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicarticle',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics_articles', to='BasicArticle.Articles'),
        ),
    ]
