# Generated by Django 2.0.6 on 2018-06-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
