# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='community',
        ),
        migrations.RemoveField(
            model_name='group',
            name='created_by',
        ),
    ]
