# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('Group', '0002_auto_20171122_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmembership', to='Group.Group')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmembership', to='auth.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupmembership', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
