# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0003_groupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupmembership', to='auth.Group'),
        ),
    ]
