# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0004_auto_20171123_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='group_admin',
            field=models.NullBooleanField(),
        ),
    ]
