# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BasicArticle', '0003_remove_articles_created_by'),
        ('Group', '0005_groupmembership_group_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouparticles', to='BasicArticle.Articles')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouparticles', to='Group.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouparticles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
