# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0006_grouparticles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouparticles',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grouparticles', to='Group.Group'),
        ),
    ]
