# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0008_remove_groupmembership_group_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
