# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 11:34
from __future__ import unicode_literals

import Group.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0011_group_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image',
            field=models.ImageField(null=True, upload_to=Group.models.get_file_path),
        ),
    ]
