# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Group', '0012_auto_20180227_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInvitations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitedat', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupinvitations', to='Group.Group')),
                ('invitedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupinvitationsinvitedby', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupinvitations', to='auth.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupinvitations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
