# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-24 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Group', '0001_initial'),
        ('BasicArticle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0001_initial'),
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitygroups',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitygroups', to='Group.Group'),
        ),
        migrations.AddField(
            model_name='communitygroups',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitygroups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communitycourses',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitycourses', to='Community.Community'),
        ),
        migrations.AddField(
            model_name='communitycourses',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitycourses', to='Course.Course'),
        ),
        migrations.AddField(
            model_name='communitycourses',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitycourses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communityarticles',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communityarticles', to='BasicArticle.Articles'),
        ),
        migrations.AddField(
            model_name='communityarticles',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communityarticles', to='Community.Community'),
        ),
        migrations.AddField(
            model_name='communityarticles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communityarticles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitycreator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Community.Community'),
        ),
    ]
