# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='tag_line',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
