# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-05 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0003_auto_20190204_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitycategory', to='Categories.Category'),
        ),
        migrations.AlterField(
            model_name='requestcommunitycreation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Categories.Category'),
        ),
    ]
