# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-05 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0003_auto_20190204_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcommunitycreation',
            name='status',
            field=models.CharField(default='Request', max_length=100, null=True),
        ),
    ]
