# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-04 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0004_auto_20190204_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcommunitycreation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category'),
        ),
    ]
