# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-07 13:52
from __future__ import unicode_literals

import Community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0004_auto_20190205_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image_thumbnail',
            field=models.ImageField(null=True, upload_to=Community.models.get_file_path),
        ),
    ]
