# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-10-10 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0005_community_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='category',
        ),
        migrations.AddField(
            model_name='community',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
