# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-07 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0006_community_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='desc_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='name_hi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
