# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-10-12 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0006_auto_20211010_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='location',
        ),
        migrations.AddField(
            model_name='community',
            name='area',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='pincode',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='state',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
