# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0006_auto_20180102_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcommunitycreation',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
