# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-10-12 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0008_community_contribution_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='contribution_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=20),
        ),
    ]
