# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-10-17 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0009_auto_20211012_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcommunitycreation',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communityparent', to='Community.Community'),
        ),
    ]
