# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 10:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0010_requestcommunitycreation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcommunitycreation',
            name='requestedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
