# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-08 09:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0011_auto_20211021_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCommunityCreationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField()),
                ('area', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('pincode', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(default='Request', max_length=100, null=True)),
                ('actionon', models.DateTimeField(auto_now_add=True, null=True)),
                ('reason', models.TextField(null=True)),
                ('actionby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='requestcommunitycreation',
            name='area',
        ),
        migrations.RemoveField(
            model_name='requestcommunitycreation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='requestcommunitycreation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='requestcommunitycreation',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='requestcommunitycreation',
            name='name',
        ),
        migrations.RemoveField(
            model_name='requestcommunitycreation',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='requestcommunitycreation',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='requestcommunitycreation',
            name='state',
        ),
        migrations.RemoveField(
            model_name='requestcommunitycreation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='requestcommunitycreation',
            name='tag_line',
        ),
        migrations.AddField(
            model_name='requestcommunitycreationdetails',
            name='requestcommunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestcommunitycreation', to='Community.RequestCommunityCreation'),
        ),
    ]
