# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0011_auto_20180102_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(null=True, upload_to='group'),
        ),
    ]
