# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0011_auto_20180102_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='forum_link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
