# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-09 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0012_auto_20211108_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcommunitycreationdetails',
            name='status',
            field=models.CharField(default='Requested', max_length=100, null=True),
        ),
    ]
