# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0012_community_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='image',
        ),
    ]
