# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0013_remove_community_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(null=True, upload_to='community'),
        ),
    ]
