# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-10 11:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0014_community_contributed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCommunityCreationAssignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignedon', models.DateTimeField(auto_now_add=True, null=True)),
                ('assignedto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='requestcommunitycreation',
            name='requestedon',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='requestcommunitycreationassignee',
            name='requestcommunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestcommunitycreationassignee', to='Community.RequestCommunityCreation'),
        ),
    ]
