# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0015_auto_20180125_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='forum_link',
        ),
        migrations.AddField(
            model_name='community',
            name='image',
            field=models.ImageField(null=True, upload_to='community'),
        ),
    ]
