# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-15 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0015_auto_20211110_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitymembership',
            name='assignedon',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
