# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-19 13:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20190318_1054'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0016_communitymembership_assignedon'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(null=True)),
                ('architecture', models.TextField(null=True)),
                ('rituals', models.TextField(null=True)),
                ('ceremonies', models.TextField(null=True)),
                ('tales', models.TextField(null=True)),
                ('moreinfo', models.TextField(null=True)),
                ('changedon', models.DateTimeField(auto_now_add=True)),
                ('originalarticles', models.TextField(null=True)),
                ('changedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mergedarticle_author', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communitymergedarticles', to='Community.Community')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mergedarticlecurrentstate', to='workflow.States')),
            ],
        ),
        migrations.CreateModel(
            name='MergedArticleStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changedon', models.DateTimeField(auto_now_add=True, null=True)),
                ('comments', models.TextField(null=True)),
                ('introduction', models.TextField(null=True)),
                ('architecture', models.TextField(null=True)),
                ('rituals', models.TextField(null=True)),
                ('ceremonies', models.TextField(null=True)),
                ('tales', models.TextField(null=True)),
                ('moreinfo', models.TextField(null=True)),
                ('changedby', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mergedarticlechangedby', to=settings.AUTH_USER_MODEL)),
                ('mergedarticle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mergedarticleinfo', to='Community.MergedArticles')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mergedarticleworkflow', to='workflow.States')),
            ],
        ),
    ]
