# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-29 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0017_mergedarticles_mergedarticlestates'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedarticles',
            name='publishedlink',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
