# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 11:38
from __future__ import unicode_literals

import Community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0018_community_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(null=True, upload_to=Community.models.get_file_path),
        ),
    ]
