# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-29 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0018_mergedarticles_publishedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedarticles',
            name='originalmedia',
            field=models.TextField(null=True),
        ),
    ]
