# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_auto_20180316_0929'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0019_auto_20180227_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityCoure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitycourses', to='Community.Community')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitycourses', to='Course.Course')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitycourses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
