# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0020_communitycoure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityCoure',
            new_name='CommunityCourse',
        ),
    ]
