# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-29 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0020_merge_20211129_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='district',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='requestcommunitycreationdetails',
            name='district',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
