# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-12-01 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0021_auto_20211129_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcommunitycreationdetails',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
