# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0021_auto_20180316_0930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommunityCourse',
            new_name='CommunityCourses',
        ),
    ]
