# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 07:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0022_auto_20180316_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communityarticles',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtyu', to='BasicArticle.Articles'),
        ),
        migrations.AlterField(
            model_name='communityarticles',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rty', to='Community.Community'),
        ),
        migrations.AlterField(
            model_name='communityarticles',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitycourses',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Community.Community'),
        ),
        migrations.AlterField(
            model_name='communitycourses',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hkg', to='Course.Course'),
        ),
        migrations.AlterField(
            model_name='communitycourses',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitygroups',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Community.Community'),
        ),
        migrations.AlterField(
            model_name='communitygroups',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jbvhgch', to='Group.Group'),
        ),
        migrations.AlterField(
            model_name='communitygroups',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jiugyug', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jnkhk', to='Community.Community'),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuc', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='communitymembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gyyuggguy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestcommunitycreation',
            name='requestedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nhyfdtdgtd', to=settings.AUTH_USER_MODEL),
        ),
    ]
