# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-12-03 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0022_auto_20211201_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='pincode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
