# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-29 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0013_auto_20180227_1136'),
        ('Community', '0022_auto_20180316_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityFeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=True)),
                ('url_type', models.CharField(max_length=25)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communityfeeds', to='BasicArticle.Articles')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communityfeeds', to='Community.Community')),
            ],
        ),
    ]
