# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0023_communityfeeds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityfeeds',
            name='article',
        ),
        migrations.RemoveField(
            model_name='communityfeeds',
            name='community',
        ),
        migrations.DeleteModel(
            name='CommunityFeeds',
        ),
    ]
