# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-05 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0024_auto_20180530_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitycourses',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitycourses', to='Community.Community'),
        ),
    ]
