# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-12-10 11:12
from __future__ import unicode_literals

import Community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0024_auto_20211210_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedarticles',
            name='document_received',
            field=models.FileField(null=True, upload_to=Community.models.get_doc_upload_path),
        ),
        migrations.AddField(
            model_name='mergedarticlestates',
            name='document_received',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
