# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0024_auto_20180614_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communityimages', to='Community.Community')),
            ],
        ),
    ]
