# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Image', '0001_initial'),
        ('Community', '0025_communityimages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communityimages',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communityimages', to='Image.Images'),
        ),
        migrations.AddField(
            model_name='communityimages',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communityimages', to=settings.AUTH_USER_MODEL),
        ),
    ]
