# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-12-17 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0026_auto_20211216_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='community',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
