# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-03 08:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0026_auto_20180928_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communityimages',
            old_name='image',
            new_name='image_resource',
        ),
    ]
