# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-12-20 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0027_auto_20211217_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='community',
            name='longitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='requestcommunitycreationdetails',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='requestcommunitycreationdetails',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
