# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-04 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Community', '0024_auto_20180614_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitymedia', to='Community.Community')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitymedia', to='Media.Media')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communitymedia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
