# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-12-20 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0028_auto_20211220_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
