# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-01-18 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0029_auto_20211220_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergedarticles',
            name='articlereferences',
            field=models.TextField(null=True),
        ),
    ]
