# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-30 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0029_community_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='forum',
        ),
    ]
