# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-02-14 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0030_mergedarticles_articlereferences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='area',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='district',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='community',
            name='state',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
