# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-25 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Community', '0028_communitymedia'),
        ('Group', '0014_groupmedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupcategories', to='Category.Category')),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groupcategories', to='Community.Community')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupcategories', to='Group.Group')),
            ],
        ),
    ]
