# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=models.ImageField(null=True, upload_to=voting.models.get_file_path),
        ),
    ]
