# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0014_auto_20180530_0735'),
        ('voting', '0008_auto_20180530_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.PositiveIntegerField()),
                ('downvote', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='state',
        ),
        migrations.RemoveField(
            model_name='articleviewlogs',
            name='article',
        ),
        migrations.RemoveField(
            model_name='community',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='communityarticles',
            name='article',
        ),
        migrations.RemoveField(
            model_name='communityarticles',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communityarticles',
            name='user',
        ),
        migrations.RemoveField(
            model_name='communitycourses',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitycourses',
            name='course',
        ),
        migrations.RemoveField(
            model_name='communitycourses',
            name='user',
        ),
        migrations.RemoveField(
            model_name='communitygroups',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitygroups',
            name='group',
        ),
        migrations.RemoveField(
            model_name='communitygroups',
            name='user',
        ),
        migrations.RemoveField(
            model_name='communitymembership',
            name='community',
        ),
        migrations.RemoveField(
            model_name='communitymembership',
            name='role',
        ),
        migrations.RemoveField(
            model_name='communitymembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='requestcommunitycreation',
            name='requestedby',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='ArticleViewLogs',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='CommunityArticles',
        ),
        migrations.DeleteModel(
            name='CommunityCourses',
        ),
        migrations.DeleteModel(
            name='CommunityGroups',
        ),
        migrations.DeleteModel(
            name='CommunityMembership',
        ),
        migrations.DeleteModel(
            name='RequestCommunityCreation',
        ),
        migrations.AddField(
            model_name='voting',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BasicArticle.Articles'),
        ),
    ]
