# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 06:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20180530_0853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrep',
            name='user',
        ),
        migrations.DeleteModel(
            name='Userrep',
        ),
    ]
