# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 10:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='user',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
