# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-01 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_auto_20180601_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='downvote',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voting',
            name='upvote',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
