# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 03:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0013_auto_20180601_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='downflag',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voting',
            name='upflag',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voting',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voting',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BasicArticle.Articles'),
        ),
    ]
