# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-02 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_auto_20180602_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='downflag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voting',
            name='upflag',
            field=models.BooleanField(default=False),
        ),
    ]
