# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 05:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0014_auto_20180530_0735'),
        ('voting', '0015_auto_20180602_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.PositiveIntegerField(default=0)),
                ('downvote', models.PositiveIntegerField(default=0)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BasicArticle.Articles')),
            ],
        ),
        migrations.RemoveField(
            model_name='voting',
            name='downvote',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='upvote',
        ),
    ]
