# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_auto_20180603_0510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Law',
            new_name='ArticleVotes',
        ),
        migrations.RenameModel(
            old_name='Voting',
            new_name='VotingFlag',
        ),
    ]
