# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-20 08:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0020_votingflag_report_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles_contributed_author', models.PositiveIntegerField(default=0)),
                ('articles_published_author', models.PositiveIntegerField(default=0)),
                ('articles_published_publisher', models.PositiveIntegerField(default=0)),
                ('articles_revised_publisher', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
