# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-10-10 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediametadata', to='Media.Media')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='mediametadata',
            name='metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediametadata', to='metadata.Metadata'),
        ),
    ]
