# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-18 10:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediametadata',
            name='media',
        ),
        migrations.RemoveField(
            model_name='mediametadata',
            name='metadata',
        ),
        migrations.DeleteModel(
            name='MediaMetadata',
        ),
    ]
