# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-08-19 13:09
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_auto_20190218_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='attrs',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
