# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-28 07:59
from __future__ import unicode_literals

import Image.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0004_auto_20180108_1504'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to=Image.models.get_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_on', models.DateTimeField(null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_author', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_publisher', to=settings.AUTH_USER_MODEL)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imageworkflow', to='workflow.States')),
            ],
        ),
    ]
