# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-09-06 13:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BasicArticle', '0020_merge_20180627_1228'),
        ('Group', '0013_groupinvitations'),
        ('Community', '0024_auto_20180614_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtherArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_ether_id', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ether_article', to='BasicArticle.Articles')),
            ],
        ),
        migrations.CreateModel(
            name='EtherCommunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_ether_id', models.TextField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ether_community', to='Community.Community')),
            ],
        ),
        migrations.CreateModel(
            name='EtherGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_ether_id', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ether_group', to='Group.Group')),
            ],
        ),
        migrations.CreateModel(
            name='EtherUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ether_id', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ether_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
