# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-25 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import workflow.views


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0002_articles_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='state',
            field=models.ForeignKey(default=workflow.views.get_initial_state, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articleworkflow', to='workflow.States'),
        ),
    ]
