# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0002_articles_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='created_by',
        ),
    ]
