# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-10-25 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0003_auto_20190325_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='introduction',
            field=models.TextField(null=True),
        ),
    ]
