# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-10 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0003_articles_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='body_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='title_hi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
