# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 11:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0004_articles_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='state',
        ),
    ]
