# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-10-25 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0004_articles_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='architecture',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='ceremonies',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='more_information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='rituals',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='articles',
            name='tales',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
