# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-07 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0005_auto_20211025_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='architecture',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='ceremonies',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='more_information',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='rituals',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='tales',
        ),
    ]
