# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0006_articles_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
