# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-11 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workflow', '0003_auto_20190318_1054'),
        ('BasicArticle', '0006_auto_20211107_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleStates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changedon', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='articles',
            name='state',
        ),
        migrations.AddField(
            model_name='articlestates',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleinfo', to='BasicArticle.Articles'),
        ),
        migrations.AddField(
            model_name='articlestates',
            name='changedby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articlechangedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articlestates',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articleworkflow', to='workflow.States'),
        ),
    ]
