# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-12 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0007_auto_20211111_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlestates',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
