# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0007_articles_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleViewLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=40)),
                ('session', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleviews', to='BasicArticle.Articles')),
            ],
        ),
    ]
