# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-12 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0008_articlestates_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlestates',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
