# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        ('BasicArticle', '0008_articleviewlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articleworkflow', to='workflow.States'),
        ),
    ]
