# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0009_articles_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to='articles'),
        ),
    ]
