# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0011_auto_20180118_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
