# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-01-16 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0011_articles_publishedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='references',
            field=models.TextField(null=True),
        ),
    ]
