# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-18 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BasicArticle', '0013_auto_20180227_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_publisher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='articles',
            name='published_on',
            field=models.DateTimeField(null=True),
        ),
    ]
