# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0013_auto_20180227_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='serverurl',
            field=models.URLField(default='localhost:9001', max_length=256),
        ),
    ]
