# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-18 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0014_auto_20180618_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='published_on',
            field=models.DateField(null=True),
        ),
    ]
