# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0014_auto_20180530_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articles',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articleworkflow', to='workflow.States'),
        ),
        migrations.AlterField(
            model_name='articleviewlogs',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articleviews', to='BasicArticle.Articles'),
        ),
    ]
