# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-10 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0014_articles_serverurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='serverurl',
            field=models.URLField(default='http://localhost:9001', max_length=256),
        ),
    ]
