# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-12 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0015_auto_20180610_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='serverurl',
            field=models.URLField(default='10.196.18.9:9001', max_length=256),
        ),
    ]
