# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-13 18:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0016_auto_20180612_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='serverurl',
        ),
    ]
