# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-14 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0017_remove_articles_serverurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='creation_complete',
            field=models.BooleanField(default=False),
        ),
    ]
