# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0018_articles_creation_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='creation_complete',
        ),
    ]
