# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-27 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BasicArticle', '0019_remove_articles_creation_complete'),
        ('BasicArticle', '0016_auto_20180619_0945'),
    ]

    operations = [
    ]
