# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 11:28
from __future__ import unicode_literals

import UserRolesPermission.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserRolesPermission', '0004_auto_20180116_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='photo',
            field=models.ImageField(upload_to=UserRolesPermission.helpers.get_file_path),
        ),
    ]
