# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRolesPermission', '0005_auto_20180227_1043'),
        ('UserRolesPermission', '0006_favourite'),
    ]

    operations = [
    ]
