# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 12:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserRolesPermission', '0008_auto_20180321_1209'),
        ('UserRolesPermission', '0008_auto_20180313_1005'),
    ]

    operations = [
    ]
