---
- hosts: all
#  become: yes
#  become_user: ubuntu
#  gather_facts: no

  tasks:
  - name: pull branch master
    git:
      repo={{ repo_url }}/{{ repo }}.git
      dest={{ repo_dir }}
      accept_hostkey=yes

#- hosts: all
#  gather_facts: no
# - tasks:
  - name: install python requirements
    pip: requirements={{ repo_dir }}/requirements.txt executable=pip3 extra_args=--upgrade


#- tasks:
  - name: django makemigrations
    shell: python3 manage.py makemigrations --noinput chdir={{django_dir}}
  - name: django migrate
    shell: ./manage.py migrate --noinput chdir={{ django_dir }}
  - name: django loaddata wf
    shell: ./manage.py loaddata workflow chdir={{ django_dir }}
  - name: djang loaaddata roles   
    shell: ./manage.py loaddata roles chdir={{ django_dir }}
  - name: djang loaaddata faq   
    shell: ./manage.py loaddata faq chdir={{ django_dir }}

