- hosts: all
  gather_facts: no

  tasks:
    - name:  Create ubuntu user
      user: name=edx password=edx generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa

    - name: Read SSH public key
      slurp: src=/home/ubuntu/.ssh/id_rsa.pub
      register: public_key
   
    - name: Running apt update
      apt: update cache=yes

    - name: Install git
      apt: name=git state=present

    - name: Copy script file
      copy:
        src: ./django.sh 
        dest: /home/edx/django.sh

    - name: Give Permission to run
      shell: sudo chmod +x django.sh

    - name: Run Script
      shell: ./django.sh edx
