# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-10 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='states',
            name='initial',
            field=models.BooleanField(default=False),
        ),
    ]
