# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 13:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transitions',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions_roles', to='auth.Group'),
        ),
    ]
