# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('workflow', '0002_transitions_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransitionsRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_transitions', to='auth.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='transitions',
            name='role',
        ),
        migrations.AddField(
            model_name='transitionsroles',
            name='transitions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transitions_roles', to='workflow.Transitions'),
        ),
    ]
