# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20180108_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transitionsroles',
            name='role',
        ),
        migrations.RemoveField(
            model_name='transitionsroles',
            name='transitions',
        ),
        migrations.DeleteModel(
            name='TransitionsRoles',
        ),
    ]
