# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-10 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0003_media_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='title_hi',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
