# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-12 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0005_auto_20211111_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediastates',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
