# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2021-11-15 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_auto_20190318_1054'),
        ('Media', '0006_mediastates_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mediacurrentstate', to='workflow.States'),
        ),
    ]
