# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2022-01-16 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0008_media_publishedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='references',
            field=models.TextField(null=True),
        ),
    ]
