# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url_name',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
