# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_url_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
