# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-06 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_auto_20180606_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='url_name',
        ),
    ]
