# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-28 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0002_auto_20181224_0729'),
        ('badges', '0002_auto_20150513_0429'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgetouser',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Community.Community'),
            preserve_default=False,
        ),
    ]
