# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-03-18 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_badgetouser_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='level',
            field=models.CharField(choices=[('1', 'Grey'), ('2', 'Red'), ('3', 'Yellow'), ('4', 'Blue'), ('5', 'Green')], max_length=1),
        ),
    ]
